/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/boombox/boombox_2k.gltf -t -r public 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane095: THREE.Mesh
    Plane095_1: THREE.Mesh
  }
  materials: {
    boombox: THREE.MeshStandardMaterial
    boombox_speakers: THREE.MeshStandardMaterial
  }
}

export function Boombox(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/boombox/boombox_2k.gltf') as GLTFResult
  return (
    <group {...props} dispose={null} scale={5}>
      <mesh geometry={nodes.Plane095.geometry} material={materials.boombox} />
      <mesh geometry={nodes.Plane095_1.geometry} material={materials.boombox_speakers} />
    </group>
  )
}

useGLTF.preload('/boombox/boombox_2k.gltf')
